version: "3"
services:
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sandstorm-backend
    ports:
      - 5432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata:
